
export const INIT_MOVIES = "INIT_MOVIES"
export const MOVIE_FETCH_REQUESTED =  "MOVIE_FETCH_REQUESTED"
export const MOVIE_FETCH_COMPLETED =  "MOVIE_FETCH_COMPLETED"
export const MOVIE_FETCH_ERROR = "MOVIE_FETCH_ERROR"
export const UPDATE_CUSTOM_ERROR_MESSAGE = "UPDATE_CUSTOM_ERROR_MESSAGE"
 