
export const INIT_USERS = "INIT_USERS"
export const USERS_FETCH_REQUESTED =  "USERS_FETCH_REQUESTED"
export const USERS_FETCH_COMPLETED =  "USERS_FETCH_COMPLETED"
export const USERS_FETCH_ERROR = "USERS_FETCH_ERROR"
export const UPDATE_CUSTOM_ERROR_MESSAGE = "UPDATE_CUSTOM_ERROR_MESSAGE"
 