
export const INIT_PROBLEMS = "INIT_PROBLEMS"
export const ADD_NEW_PROLEM = "ADD_NEW_PROLEM"
export const UPDATE_ACTIVE_SECTION = "UPDATE_ACTIVE_SECTION"
export const UPDATE_SOLN_STATUS = "UPDATE_SOLN_STATUS"
export const UPDATE_SECTION_STATUS = "UPDATE_SECTION_STATUS"

export const INIT_MOVIES = "INIT_MOVIES"
export const MOVIE_FETCH_REQUESTED =  "MOVIE_FETCH_REQUESTED"
export const MOVIE_FETCH_COMPLETED =  "MOVIE_FETCH_COMPLETED"
export const MOVIE_FETCH_ERROR = "MOVIE_FETCH_ERROR"